name: medioambiente_rd
description: App del Ministerio de Medio Ambiente RD
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  video_player: ^2.8.1
  flutter_map: ^5.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/